// <auto-generated />
using System;
using Dyrepermen.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dyrepermen.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DyrepermenDbContext))]
    partial class DyrepermenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Behandling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Dato")
                        .HasColumnType("date")
                        .HasColumnName("dato");

                    b.Property<int>("DyrId")
                        .HasColumnType("integer")
                        .HasColumnName("dyr_id");

                    b.Property<DateOnly?>("NesteDato")
                        .HasColumnType("date")
                        .HasColumnName("neste_dato");

                    b.Property<string>("Notat")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notat");

                    b.Property<string>("Preparat")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("preparat");

                    b.Property<char>("Type")
                        .HasColumnType("char(1)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_behandling");

                    b.HasIndex("DyrId")
                        .HasDatabaseName("ix_behandling_dyr_id");

                    b.HasIndex("NesteDato")
                        .HasDatabaseName("ix_behandling_neste")
                        .HasFilter("neste_dato IS NOT NULL");

                    b.ToTable("behandling", null, t =>
                        {
                            t.HasCheckConstraint("ck_behandling_type", "type IN ('V','O','F','K','T')");
                        });
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Bruker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.Property<string>("Visningsnavn")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("visningsnavn");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("ix_asp_net_users_epost");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ux_asp_net_users_brukernavn");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Dokument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("DyrId")
                        .HasColumnType("integer")
                        .HasColumnName("dyr_id");

                    b.Property<string>("Filnavn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("filnavn");

                    b.Property<char>("Kategori")
                        .HasColumnType("char(1)")
                        .HasColumnName("kategori");

                    b.Property<DateOnly>("OpplastetDato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("opplastet_dato")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("Originalnavn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("originalnavn");

                    b.HasKey("Id")
                        .HasName("pk_dokument");

                    b.HasIndex("DyrId")
                        .HasDatabaseName("ix_dokument_dyr_id");

                    b.ToTable("dokument", null, t =>
                        {
                            t.HasCheckConstraint("ck_dokument_kategori", "kategori IN ('V','J','K','A')");
                        });
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Dose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("GittAvBrukerId")
                        .HasColumnType("integer")
                        .HasColumnName("gitt_av_bruker_id");

                    b.Property<DateTimeOffset>("GittTid")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gitt_tid");

                    b.Property<int>("MedisinId")
                        .HasColumnType("integer")
                        .HasColumnName("medisin_id");

                    b.HasKey("Id")
                        .HasName("pk_dose");

                    b.HasIndex("GittAvBrukerId")
                        .HasDatabaseName("ix_dose_gitt_av_bruker_id");

                    b.HasIndex("MedisinId", "GittTid")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_dose_medisin_tid");

                    b.ToTable("dose", (string)null);
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Dyr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("aktiv");

                    b.Property<char>("Art")
                        .HasColumnType("char(1)")
                        .HasColumnName("art");

                    b.Property<string>("BildeFilnavn")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("bilde_filnavn");

                    b.Property<string>("ChipNr")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("chip_nr");

                    b.Property<DateOnly?>("Fodselsdato")
                        .HasColumnType("date")
                        .HasColumnName("fodselsdato");

                    b.Property<bool>("ForingsloggAktiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("foringslogg_aktiv");

                    b.Property<bool>("ForplanAktiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("forplan_aktiv");

                    b.Property<int>("HusstandId")
                        .HasColumnType("integer")
                        .HasColumnName("husstand_id");

                    b.Property<bool>("Kastrert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("kastrert");

                    b.Property<char>("Kjonn")
                        .HasColumnType("char(1)")
                        .HasColumnName("kjonn");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("navn");

                    b.Property<string>("Rase")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("rase");

                    b.Property<string>("RegNrNkk")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reg_nr_nkk");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_dyr");

                    b.HasIndex("ChipNr")
                        .IsUnique()
                        .HasDatabaseName("ux_dyr_chip")
                        .HasFilter("chip_nr IS NOT NULL");

                    b.HasIndex("HusstandId")
                        .HasDatabaseName("ix_dyr_husstand");

                    b.ToTable("dyr", null, t =>
                        {
                            t.HasCheckConstraint("ck_dyr_art", "art IN ('H','K')");

                            t.HasCheckConstraint("ck_dyr_chip_lengde", "chip_nr IS NULL OR char_length(chip_nr) = 15");

                            t.HasCheckConstraint("ck_dyr_kjonn", "kjonn IN ('T','H')");
                        });
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Foring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("DyrId")
                        .HasColumnType("integer")
                        .HasColumnName("dyr_id");

                    b.Property<string>("Fornavn")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("fornavn");

                    b.Property<int?>("GittAvBrukerId")
                        .HasColumnType("integer")
                        .HasColumnName("gitt_av_bruker_id");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("kommentar");

                    b.Property<int?>("MengdeGram")
                        .HasColumnType("integer")
                        .HasColumnName("mengde_gram");

                    b.Property<DateTimeOffset>("Tidspunkt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tidspunkt")
                        .HasDefaultValueSql("now()");

                    b.Property<char>("Type")
                        .HasColumnType("char(1)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_foring");

                    b.HasIndex("GittAvBrukerId")
                        .HasDatabaseName("ix_foring_gitt_av_bruker_id");

                    b.HasIndex("DyrId", "Tidspunkt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_foring_dyr_tid");

                    b.ToTable("foring", null, t =>
                        {
                            t.HasCheckConstraint("ck_foring_mengde", "mengde_gram IS NULL OR mengde_gram > 0");

                            t.HasCheckConstraint("ck_foring_type", "type IN ('M','G')");
                        });
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Forplan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("aktiv");

                    b.Property<int>("AntallMaltider")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("antall_maltider");

                    b.Property<int>("DyrId")
                        .HasColumnType("integer")
                        .HasColumnName("dyr_id");

                    b.Property<string>("Fornavn")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("fornavn");

                    b.Property<int?>("GramPerDag")
                        .HasColumnType("integer")
                        .HasColumnName("gram_per_dag");

                    b.Property<char>("Metode")
                        .HasColumnType("char(1)")
                        .HasColumnName("metode");

                    b.Property<string>("Notat")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("notat");

                    b.Property<DateOnly>("OpprettetDato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("opprettet_dato")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<int?>("ProsentTidels")
                        .HasColumnType("integer")
                        .HasColumnName("prosent_tidels");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_forplan");

                    b.HasIndex("DyrId")
                        .IsUnique()
                        .HasDatabaseName("ux_forplan_aktiv")
                        .HasFilter("aktiv");

                    b.ToTable("forplan", null, t =>
                        {
                            t.HasCheckConstraint("ck_forplan_maltider", "antall_maltider BETWEEN 1 AND 6");

                            t.HasCheckConstraint("ck_forplan_metode", "metode IN ('P','G')");

                            t.HasCheckConstraint("ck_forplan_verdi", "   (metode = 'P' AND prosent_tidels IS NOT NULL\n                 AND prosent_tidels BETWEEN 1 AND 300\n                 AND gram_per_dag IS NULL)\nOR (metode = 'G' AND gram_per_dag IS NOT NULL\n                 AND gram_per_dag > 0\n                 AND prosent_tidels IS NULL)");
                        });
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Forsikring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("ArspremieKr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("arspremie_kr");

                    b.Property<int>("DyrId")
                        .HasColumnType("integer")
                        .HasColumnName("dyr_id");

                    b.Property<int>("EgenandelFastKr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("egenandel_fast_kr");

                    b.Property<int>("EgenandelVariabelTidels")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("egenandel_variabel_tidels");

                    b.Property<DateOnly?>("FornyesDato")
                        .HasColumnType("date")
                        .HasColumnName("fornyes_dato");

                    b.Property<int>("ForsikringsbelopKr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("forsikringsbelop_kr");

                    b.Property<string>("PoliseNr")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("polise_nr");

                    b.Property<string>("Selskap")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("selskap");

                    b.HasKey("Id")
                        .HasName("pk_forsikring");

                    b.HasIndex("DyrId")
                        .HasDatabaseName("ix_forsikring_dyr_id");

                    b.HasIndex("FornyesDato")
                        .HasDatabaseName("ix_forsikring_fornyes")
                        .HasFilter("fornyes_dato IS NOT NULL");

                    b.ToTable("forsikring", null, t =>
                        {
                            t.HasCheckConstraint("ck_forsikring_variabel", "egenandel_variabel_tidels BETWEEN 0 AND 1000");
                        });
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Handleliste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("Antall")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("antall");

                    b.Property<int?>("DyrId")
                        .HasColumnType("integer")
                        .HasColumnName("dyr_id");

                    b.Property<int>("HusstandId")
                        .HasColumnType("integer")
                        .HasColumnName("husstand_id");

                    b.Property<int?>("OpprettetAvBrukerId")
                        .HasColumnType("integer")
                        .HasColumnName("opprettet_av_bruker_id");

                    b.Property<DateOnly>("OpprettetDato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("opprettet_dato")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<char>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("status");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tekst");

                    b.HasKey("Id")
                        .HasName("pk_handleliste");

                    b.HasIndex("DyrId")
                        .HasDatabaseName("ix_handleliste_dyr_id");

                    b.HasIndex("HusstandId")
                        .HasDatabaseName("ix_handleliste_aktiv")
                        .HasFilter("status = 'A'");

                    b.HasIndex("OpprettetAvBrukerId")
                        .HasDatabaseName("ix_handleliste_opprettet_av_bruker_id");

                    b.ToTable("handleliste", null, t =>
                        {
                            t.HasCheckConstraint("ck_handleliste_status", "status IN ('A','K')");
                        });
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Husstand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("navn");

                    b.Property<DateOnly>("OpprettetDato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("opprettet_dato")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.HasKey("Id")
                        .HasName("pk_husstand");

                    b.ToTable("husstand", (string)null);
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.HusstandInnstilling", b =>
                {
                    b.Property<int>("HusstandId")
                        .HasColumnType("integer")
                        .HasColumnName("husstand_id");

                    b.Property<bool>("ForingsloggStandard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("foringslogg_standard");

                    b.Property<bool>("ForplanStandard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("forplan_standard");

                    b.Property<bool>("GodbitloggAktiv")
                        .HasColumnType("boolean")
                        .HasColumnName("godbitlogg_aktiv");

                    b.Property<bool>("VarslerAktiv")
                        .HasColumnType("boolean")
                        .HasColumnName("varsler_aktiv");

                    b.HasKey("HusstandId")
                        .HasName("pk_husstand_innstilling");

                    b.ToTable("husstand_innstilling", (string)null);
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.HusstandInvitasjon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Epost")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("epost");

                    b.Property<int>("HusstandId")
                        .HasColumnType("integer")
                        .HasColumnName("husstand_id");

                    b.Property<int?>("InnlostAvBrukerId")
                        .HasColumnType("integer")
                        .HasColumnName("innlost_av_bruker_id");

                    b.Property<DateTimeOffset?>("InnlostTid")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("innlost_tid");

                    b.Property<int?>("OpprettetAvBrukerId")
                        .HasColumnType("integer")
                        .HasColumnName("opprettet_av_bruker_id");

                    b.Property<DateOnly>("OpprettetDato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("opprettet_dato")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<char>("Rolle")
                        .HasColumnType("char(1)")
                        .HasColumnName("rolle");

                    b.HasKey("Id")
                        .HasName("pk_husstand_invitasjon");

                    b.HasIndex("HusstandId")
                        .HasDatabaseName("ix_husstand_invitasjon_husstand_id");

                    b.HasIndex("InnlostAvBrukerId")
                        .HasDatabaseName("ix_husstand_invitasjon_innlost_av_bruker_id");

                    b.HasIndex("OpprettetAvBrukerId")
                        .HasDatabaseName("ix_husstand_invitasjon_opprettet_av_bruker_id");

                    b.ToTable("husstand_invitasjon", (string)null);
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Husstandsmedlemskap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("BrukerId")
                        .HasColumnType("integer")
                        .HasColumnName("bruker_id");

                    b.Property<int>("HusstandId")
                        .HasColumnType("integer")
                        .HasColumnName("husstand_id");

                    b.Property<DateOnly>("OpprettetDato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("opprettet_dato")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<char>("Rolle")
                        .HasColumnType("char(1)")
                        .HasColumnName("rolle");

                    b.HasKey("Id")
                        .HasName("pk_husstandsmedlemskap");

                    b.HasIndex("BrukerId")
                        .HasDatabaseName("ix_medlemskap_bruker");

                    b.HasIndex("HusstandId", "BrukerId")
                        .IsUnique()
                        .HasDatabaseName("ux_medlemskap_husstand_bruker");

                    b.ToTable("husstandsmedlemskap", null, t =>
                        {
                            t.HasCheckConstraint("ck_medlemskap_rolle", "rolle IN ('B','G')");
                        });
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Informasjon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("DyrId")
                        .HasColumnType("integer")
                        .HasColumnName("dyr_id");

                    b.Property<int>("HusstandId")
                        .HasColumnType("integer")
                        .HasColumnName("husstand_id");

                    b.Property<int?>("OpprettetAvBrukerId")
                        .HasColumnType("integer")
                        .HasColumnName("opprettet_av_bruker_id");

                    b.Property<DateOnly>("OpprettetDato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("opprettet_dato")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("tekst");

                    b.Property<string>("Tittel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("tittel");

                    b.HasKey("Id")
                        .HasName("pk_informasjon");

                    b.HasIndex("DyrId")
                        .HasDatabaseName("ix_informasjon_dyr_id");

                    b.HasIndex("HusstandId")
                        .HasDatabaseName("ix_informasjon_husstand");

                    b.HasIndex("OpprettetAvBrukerId")
                        .HasDatabaseName("ix_informasjon_opprettet_av_bruker_id");

                    b.ToTable("informasjon", (string)null);
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Medisin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("dose");

                    b.Property<int>("DyrId")
                        .HasColumnType("integer")
                        .HasColumnName("dyr_id");

                    b.Property<int>("IntervallTimer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("intervall_timer");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("navn");

                    b.Property<DateOnly?>("SluttDato")
                        .HasColumnType("date")
                        .HasColumnName("slutt_dato");

                    b.Property<DateOnly>("StartDato")
                        .HasColumnType("date")
                        .HasColumnName("start_dato");

                    b.HasKey("Id")
                        .HasName("pk_medisin");

                    b.HasIndex("DyrId")
                        .HasDatabaseName("ix_medisin_dyr_id");

                    b.ToTable("medisin", (string)null);
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Vekt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Dato")
                        .HasColumnType("date")
                        .HasColumnName("dato");

                    b.Property<int>("DyrId")
                        .HasColumnType("integer")
                        .HasColumnName("dyr_id");

                    b.Property<int?>("RegistrertAvBrukerId")
                        .HasColumnType("integer")
                        .HasColumnName("registrert_av_bruker_id");

                    b.Property<int>("VektGram")
                        .HasColumnType("integer")
                        .HasColumnName("vekt_gram");

                    b.HasKey("Id")
                        .HasName("pk_vekt");

                    b.HasIndex("RegistrertAvBrukerId")
                        .HasDatabaseName("ix_vekt_registrert_av_bruker_id");

                    b.HasIndex("DyrId", "Dato")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_vekt_dyr_dato");

                    b.ToTable("vekt", null, t =>
                        {
                            t.HasCheckConstraint("ck_vekt_gram", "vekt_gram > 0");
                        });
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Vetbesok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Arsak")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("arsak");

                    b.Property<DateOnly>("Dato")
                        .HasColumnType("date")
                        .HasColumnName("dato");

                    b.Property<string>("Diagnose")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("diagnose");

                    b.Property<int>("DyrId")
                        .HasColumnType("integer")
                        .HasColumnName("dyr_id");

                    b.Property<bool>("ForsikringKrevd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("forsikring_krevd");

                    b.Property<string>("Klinikk")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("klinikk");

                    b.Property<int>("KostnadKr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("kostnad_kr");

                    b.HasKey("Id")
                        .HasName("pk_vetbesok");

                    b.HasIndex("DyrId")
                        .HasDatabaseName("ix_vetbesok_dyr_id");

                    b.ToTable("vetbesok", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_asp_net_roles_navn");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Behandling", b =>
                {
                    b.HasOne("Dyrepermen.Domain.Entities.Dyr", "Dyr")
                        .WithMany("Behandlinger")
                        .HasForeignKey("DyrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_behandling_dyr_dyr_id");

                    b.Navigation("Dyr");
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Dokument", b =>
                {
                    b.HasOne("Dyrepermen.Domain.Entities.Dyr", "Dyr")
                        .WithMany("Dokumenter")
                        .HasForeignKey("DyrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dokument_dyr_dyr_id");

                    b.Navigation("Dyr");
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Dose", b =>
                {
                    b.HasOne("Dyrepermen.Domain.Entities.Bruker", "GittAv")
                        .WithMany()
                        .HasForeignKey("GittAvBrukerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_dose_asp_net_users_gitt_av_bruker_id");

                    b.HasOne("Dyrepermen.Domain.Entities.Medisin", "Medisin")
                        .WithMany("Doser")
                        .HasForeignKey("MedisinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dose_medisin_medisin_id");

                    b.Navigation("GittAv");

                    b.Navigation("Medisin");
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Dyr", b =>
                {
                    b.HasOne("Dyrepermen.Domain.Entities.Husstand", "Husstand")
                        .WithMany("Dyr")
                        .HasForeignKey("HusstandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dyr_husstand_husstand_id");

                    b.Navigation("Husstand");
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Foring", b =>
                {
                    b.HasOne("Dyrepermen.Domain.Entities.Dyr", "Dyr")
                        .WithMany("Foringer")
                        .HasForeignKey("DyrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_foring_dyr_dyr_id");

                    b.HasOne("Dyrepermen.Domain.Entities.Bruker", "GittAv")
                        .WithMany()
                        .HasForeignKey("GittAvBrukerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_foring_asp_net_users_gitt_av_bruker_id");

                    b.Navigation("Dyr");

                    b.Navigation("GittAv");
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Forplan", b =>
                {
                    b.HasOne("Dyrepermen.Domain.Entities.Dyr", "Dyr")
                        .WithMany("Forplaner")
                        .HasForeignKey("DyrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_forplan_dyr_dyr_id");

                    b.Navigation("Dyr");
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Forsikring", b =>
                {
                    b.HasOne("Dyrepermen.Domain.Entities.Dyr", "Dyr")
                        .WithMany("Forsikringer")
                        .HasForeignKey("DyrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_forsikring_dyr_dyr_id");

                    b.Navigation("Dyr");
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Handleliste", b =>
                {
                    b.HasOne("Dyrepermen.Domain.Entities.Dyr", "Dyr")
                        .WithMany()
                        .HasForeignKey("DyrId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_handleliste_dyr_dyr_id");

                    b.HasOne("Dyrepermen.Domain.Entities.Husstand", "Husstand")
                        .WithMany("Handleliste")
                        .HasForeignKey("HusstandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_handleliste_husstand_husstand_id");

                    b.HasOne("Dyrepermen.Domain.Entities.Bruker", "OpprettetAv")
                        .WithMany()
                        .HasForeignKey("OpprettetAvBrukerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_handleliste_asp_net_users_opprettet_av_bruker_id");

                    b.Navigation("Dyr");

                    b.Navigation("Husstand");

                    b.Navigation("OpprettetAv");
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.HusstandInnstilling", b =>
                {
                    b.HasOne("Dyrepermen.Domain.Entities.Husstand", "Husstand")
                        .WithOne("Innstilling")
                        .HasForeignKey("Dyrepermen.Domain.Entities.HusstandInnstilling", "HusstandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_husstand_innstilling_husstand_husstand_id");

                    b.Navigation("Husstand");
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.HusstandInvitasjon", b =>
                {
                    b.HasOne("Dyrepermen.Domain.Entities.Husstand", "Husstand")
                        .WithMany("Invitasjoner")
                        .HasForeignKey("HusstandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_husstand_invitasjon_husstand_husstand_id");

                    b.HasOne("Dyrepermen.Domain.Entities.Bruker", "InnlostAv")
                        .WithMany()
                        .HasForeignKey("InnlostAvBrukerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_husstand_invitasjon_asp_net_users_innlost_av_bruker_id");

                    b.HasOne("Dyrepermen.Domain.Entities.Bruker", "OpprettetAv")
                        .WithMany()
                        .HasForeignKey("OpprettetAvBrukerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_husstand_invitasjon_asp_net_users_opprettet_av_bruker_id");

                    b.Navigation("Husstand");

                    b.Navigation("InnlostAv");

                    b.Navigation("OpprettetAv");
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Husstandsmedlemskap", b =>
                {
                    b.HasOne("Dyrepermen.Domain.Entities.Bruker", "Bruker")
                        .WithMany("Medlemskap")
                        .HasForeignKey("BrukerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_husstandsmedlemskap_users_bruker_id");

                    b.HasOne("Dyrepermen.Domain.Entities.Husstand", "Husstand")
                        .WithMany("Medlemskap")
                        .HasForeignKey("HusstandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_husstandsmedlemskap_husstand_husstand_id");

                    b.Navigation("Bruker");

                    b.Navigation("Husstand");
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Informasjon", b =>
                {
                    b.HasOne("Dyrepermen.Domain.Entities.Dyr", "Dyr")
                        .WithMany()
                        .HasForeignKey("DyrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_informasjon_dyr_dyr_id");

                    b.HasOne("Dyrepermen.Domain.Entities.Husstand", "Husstand")
                        .WithMany()
                        .HasForeignKey("HusstandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_informasjon_husstand_husstand_id");

                    b.HasOne("Dyrepermen.Domain.Entities.Bruker", "OpprettetAv")
                        .WithMany()
                        .HasForeignKey("OpprettetAvBrukerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_informasjon_asp_net_users_opprettet_av_bruker_id");

                    b.Navigation("Dyr");

                    b.Navigation("Husstand");

                    b.Navigation("OpprettetAv");
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Medisin", b =>
                {
                    b.HasOne("Dyrepermen.Domain.Entities.Dyr", "Dyr")
                        .WithMany("Medisiner")
                        .HasForeignKey("DyrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medisin_dyr_dyr_id");

                    b.Navigation("Dyr");
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Vekt", b =>
                {
                    b.HasOne("Dyrepermen.Domain.Entities.Dyr", "Dyr")
                        .WithMany("Vekter")
                        .HasForeignKey("DyrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vekt_dyr_dyr_id");

                    b.HasOne("Dyrepermen.Domain.Entities.Bruker", "RegistrertAv")
                        .WithMany()
                        .HasForeignKey("RegistrertAvBrukerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_vekt_asp_net_users_registrert_av_bruker_id");

                    b.Navigation("Dyr");

                    b.Navigation("RegistrertAv");
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Vetbesok", b =>
                {
                    b.HasOne("Dyrepermen.Domain.Entities.Dyr", "Dyr")
                        .WithMany("Vetbesok")
                        .HasForeignKey("DyrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vetbesok_dyr_dyr_id");

                    b.Navigation("Dyr");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Dyrepermen.Domain.Entities.Bruker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Dyrepermen.Domain.Entities.Bruker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Dyrepermen.Domain.Entities.Bruker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Dyrepermen.Domain.Entities.Bruker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Bruker", b =>
                {
                    b.Navigation("Medlemskap");
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Dyr", b =>
                {
                    b.Navigation("Behandlinger");

                    b.Navigation("Dokumenter");

                    b.Navigation("Foringer");

                    b.Navigation("Forplaner");

                    b.Navigation("Forsikringer");

                    b.Navigation("Medisiner");

                    b.Navigation("Vekter");

                    b.Navigation("Vetbesok");
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Husstand", b =>
                {
                    b.Navigation("Dyr");

                    b.Navigation("Handleliste");

                    b.Navigation("Innstilling");

                    b.Navigation("Invitasjoner");

                    b.Navigation("Medlemskap");
                });

            modelBuilder.Entity("Dyrepermen.Domain.Entities.Medisin", b =>
                {
                    b.Navigation("Doser");
                });
#pragma warning restore 612, 618
        }
    }
}
